export const emotions = [
  "enttäuscht",
  "gespannt",
  "angespannt",
  "vorfreudig",
  "überrascht",
  "stolz",
  "gelangweilt",
  "zuversichtlich",
  "neugierig",
  "belustigt",
  "neugierig",
  "eifersüchtig",
  "verletzt",
  "beleidigt",
  "aggressiv",
  "zornig",
  "gleichgültig",
  "angriffslustig",
  "emotional",
  "verspielt",
  "geschmeichelt",
  "überlegen",
  "erstaunt",
  "beglückt",
  "unaufgeregt",
  "verbittert",
  "zufrieden",
  "ängstlich",
  "schüchtern",
  "aufbrausend",
]

export const objects = [
  "altes Telefon",
  "Schaufensterpuppe",
  "Snowboardschuh",
  "Lederjacke",
  "Lupe",
  "Armreif",
  "Ohrringe",
  "Plastik-Flamingo",
  "pinke Sonnenbrille",
  "Trinkflasche",
  "Gitarre",
  "Porzellan",
  "Spiegel",
  "Glasvase",
  "Koffer",
  "Radio",
]

export const places = [
  "am Meer",
  "am Tisch",
  "Bahnhof/Zug",
  "Bauernhof",
  "Bauernhof",
  "Berg",
  "Büro",
  "einsame Insel",
  "Fabrik",
  "Flohmarkt",
  "Flughafen",
  "Garten",
  "im Fluss",
  "Keller",
  "Kino",
  "Museum",
  "Schule",
  "Schule",
  "Stadt",
  "Strand",
  "Strand",
  "Wald",
  "WC",
  "Weltall/Raumschiff",
  "Zoo",
]
